name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make test files executable
      run: find test-bin -type f -exec chmod a+x {} +    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
